version: "3"

services:
  mysqldb:
    image: mysql
    container_name: mysqldb_container
    ports:
      - "3366:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=books
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
